SELECT * 
FROM sales_data;

SELECT CUSTOMERNAME, 
COUNTRY, 
SALES
FROM sales_data
WHERE COUNTRY = 'USA'
SELECT CUSTOMERNAME, 
SALES
FROM sales_data
ORDER BY SALES DESC;
SELECT SUM(SALES) AS TOTALREVENUE
FROM sales_data;
SELECT AVG(SALES) AS AVERAGESALES
FROM sales_data;
SELECT COUNT(DISTINCT CUSTOMERNAME) 
AS TOTALCUSTOMERS
FROM sales_data;
SELECT COUNTRY, 
SUM(SALES) AS REVENUE
FROM sales_data
GROUP BY COUNTRY
ORDER BY REVENUE DESC;
SELECT PRODUCTLINE, 
SUM(SALES) AS TOTALSALES
FROM sales_data
GROUP BY PRODUCTLINE
ORDER BY TOTALSALES DESC;
SELECT COUNTRY, 
SUM(SALES) AS REVENUE
FROM sales_data
GROUP BY COUNTRY
HAVING SUM(SALES) > 500000;

SELECT TOP 10 CUSTOMERNAME, 
SUM(SALES) AS TOTALSPENT
FROM sales_data
GROUP BY CUSTOMERNAME
ORDER BY TOTALSPENT DESC;

SELECT MONTH_ID, 
SUM(SALES) AS MONTHLYREVENUE
FROM sales_data
GROUP BY MONTH_ID
ORDER BY MONTHLYREVENUE DESC;
SELECT YEAR_ID, 
SUM(SALES) AS YEARLYREVENUE
FROM sales_data
GROUP BY YEAR_ID
ORDER BY YEARLYREVENUE DESC;

SELECT CUSTOMERNAME,
SUM(SALES) AS TOTALSALES,
RANK() OVER (
ORDER BY SUM(SALES) DESC
) AS SALESRANK
FROM sales_data
GROUP BY CUSTOMERNAME;

SELECT COUNTRY,
CUSTOMERNAME,
SALES,
ROW_NUMBER() OVER
(
PARTITION BY COUNTRY
ORDER BY SALES DESC
) AS COUNTRYRANK
FROM sales_data;

SELECT CUSTOMERNAME,
SALES,
ROW_NUMBER() OVER
(
ORDER BY SALES DESC
) AS ROWNUM
FROM sales_data;

SELECT CUSTOMERNAME,
SALES
FROM sales_data
WHERE SALES >
(
SELECT AVG(SALES)
FROM sales_data
);
